### ISSUE TITLE
Lessons refactored

### ISSUE THREAD

**Issue by allensoberano** [learn-co-curriculum/oxford-comma#10]
Not sure if this already exists here and I haven't found it. But it would be very nice and helpful if after we passed the lesson correctly that we were able to see how a more experienced programmer would write the program. That way we can refactor our code to see better ways of doing the same thing.

**Comment by AnnJohn** [comment]
@allensoberano Thanks for raising the issue. This is actually something that we're working on- lab tutorials where you'll see how instructors (who are experienced programmers) would go approach a lab. I'm putting this issue on icebox as it's something that we'll definitely resolve in the future. Thanks again!
