### ISSUE TITLE
In the array to string paragraph of the oxford comma module

### ISSUE THREAD

**Issue by lqf2b8** [learn-co-curriculum/oxford-comma#11]
you give an example of using the join method with a smiley face argument and show the following example:

["a", "b", "c"].join(" :-) ")
  => "a :-) b :-) c :-)"

In my opinion there should not be a :-) after the c in the string output because join does not input its argument after the final element of the array.

I feel that it should be the following:

["a", "b", "c"].join(" :-) ")
  => "a :-) b :-) c"

Hope that made sense. If not let me know and I will try to rephrase.

thanks

**Comment by AnnJohn** [comment]
@lqf2b8 Thanks for raising this issue. We'll get to this as soon as we can, but since it seems like you want immediate clarification, please use the "Ask a Question" tool in Learn and one of our instructors will get back to you soon. Thanks again.

**Comment by lqf2b8** [comment]
AnnJohn,

Sorry but I guess I was ambiguous. I was not raising a question. I was pointing out that the example in the "array to string" paragraph that uses the :-) was incorrect. The :-) after the c in the output should not be there.

Sorry for the confusion. 

Thanks again,
Lucas

**Comment by AnnJohn** [comment]
@lqf2b8 Thanks for the clarification!

**Comment by SophieDeBenedetto** [comment]
@lqf2b8 thanks for the input! fixing right now.
