### ISSUE TITLE
Who care about an Oxford Comma? I do, that's who! 

### ISSUE THREAD

**Issue by jaywood128** [learn-co-curriculum/oxford-comma#12]
def oxford_comma(array)
 if array.length == 1
   array.join

    elsif array.length == 2
      array.join(" and ")

    elsif array.length == 3
      array.join(",") 
      

  end
end
1) #oxford_comma adds commas plus a final 'and' when given a 3-element array
     Failure/Error: expect(oxford_comma(["kiwi", "durian", "starfruit"])).to eq("kiwi, durian, and starfruit")
       expected: "kiwi, durian, and starfruit"
            got: ["kiwi", "durian", "starfruit", "end"]
Passing 2/4 

Why is .join not working for my second elsif? I am returning an array, which is not what I want. I am trying to convert the array to a string. I am also trying to add commas, and an " and, " at the end of the array. The lab hints about the shovel method, however, that method can't insert the "and" where I need it. Is there like a splice or insert the ", and " into the end of the string? Any help would be appreciated!

**Comment by drakeltheryuujin** [comment]
Hi @jaywood128 ,

[Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the curriculum — not difficulties solving a lab, mistakes fixed via [a quick edit](http://help.learn.co/improving-learn/contributing-to-lessons/can-i-edit-a-lesson), or bugs with the Learn platform (such as [lights not turning green](http://help.learn.co/your-learn-account/learn-lights/lights-not-turning-green) or [IDE issues](http://help.learn.co/the-learn-ide)).

This issue would be perfect for the [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ) feature, where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-support/does-my-program-or-course-have-technical-coach-support)) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out [this helpful article](http://help.learn.co/ask-a-question/how-to-optimize-time-in-ask-a-question) in the [Learn Help Center](http://help.learn.co/).

If, after consulting the Help Center and AAQ, you still feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 💙
