### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by MarcRodrigFelix** [learn-co-curriculum/oxford-comma#13]
"Formatting" is misspelled in the lab tests section.

"#oxford_comma
  returns a string without any additional **fomatting** when given a 1-element array"

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
