### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by dancinghoneybees** [learn-co-curriculum/oxford-comma#9]
Hi,

I think there is a typo in this line:
"The .join method, when called on *a string*, will convert it into *an array*."
Think it should read, " The .join method, when called on *an array*, will convert it into *a string*."

And a type on this line, "But calling .join on the same *string* and giving it an argument of a " :-) " "
should be "But calling .join on the same *array* and giving it an argument of a " :-) "

**Comment by AnnJohn** [comment]
@SophieDeBenedetto  due 8/20
